### ISSUE TITLE
java.lang.IllegalArgumentException: provider doesn't exisit: null

### ISSUE THREAD

**Issue by eileenfan** [Phantast/smartnavi#19]
//package name: com.ilm.sandwich
//version: 2.2.1f
 java.lang.RuntimeException: Unable to resume activity {com.ilm.sandwich/com.ilm.sandwich.OsmMap}: java.lang.IllegalArgumentException: provider doesn't exisit: null
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2790)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2266)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.IllegalArgumentException: provider doesn't exisit: null
 	at android.os.Parcel.readException(Parcel.java:1435)
 	at android.os.Parcel.readException(Parcel.java:1385)
 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:540)
 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:836)
 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:430)
 	at com.ilm.sandwich.tools.Locationer.startLocationUpdates(Locationer.java:152)
 	at com.ilm.sandwich.OsmMap.onResume(OsmMap.java:524)
 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
 	at android.app.Activity.performResume(Activity.java:5211)
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2780)

**Comment by eileenfan** [comment]
The provider(network or gps) is null or doesn't exist on some device, so even if you start corresponding services, it still doesn’t work.
